SELECT
    ROWNUM AS "Nr",
    SKU.CLIENT_ID                   AS "Client ID",
    SKU.SKU_ID                      AS SKU,
    SKU.DESCRIPTION                 AS "Description",
    SKU.USER_DEF_TYPE_3             AS "Division",
    SKU.PRODUCT_GROUP               AS "Product Group",
    SKU.USER_DEF_TYPE_6             AS "Brand",
    SKU.USER_DEF_TYPE_4             AS "UOM",
    SKU.EACH_HEIGHT                 AS "Each Height",
    SKU.EACH_WIDTH                  AS "Each Width",
    SKU.EACH_DEPTH                  AS "Each Depth",
    SKU.EACH_WEIGHT                 AS "Each Weight",
    SKU.EACH_VOLUME                 AS "Each Volume",
    SKU.PACKED_HEIGHT               AS "Packed Height",
    SKU.PACKED_WIDTH                AS "Packed Width",
    SKU.PACKED_DEPTH                AS "Packed Depth",
    SKU.PACKED_VOLUME               AS "Packed Volume",
    SKU.PACKED_WEIGHT               AS "Packed Weight",
    SKU.BEAM_UNITS                  AS "Beam Units",
    SKU.EACH_VALUE                  AS "Each Value",
    SKU.ALLOCATION_GROUP            AS "Allocation Group",
    SKU.PUTAWAY_GROUP               AS "Putaway Group",
    SKU.HAZMAT                      AS "Hazmat",
    SKU.HAZMAT_ID                   AS "Hazmat ID",
    SKU.USER_DEF_TYPE_1             AS "Default Building Code",
    SKU.USER_DEF_TYPE_2             AS "Retail Barcode",
    SKU.EAN                         AS EAN,
    SKU.UPC                         AS UPC,
    SKU.USER_DEF_TYPE_5             AS "Supplier Product Code",
    SKU.USER_DEF_TYPE_7             AS "Storage Method",
    SKU.USER_DEF_TYPE_8             AS "Rework Text",
    SKU.USER_DEF_NUM_1              AS "Clothing Putaway Group",
    SKU.USER_DEF_NUM_2              AS "Pack Config Outer / Pallet QTY",
    SKU.USER_DEF_NUM_3              AS "Pallet Qty",
    SKU.USER_DEF_NUM_4              AS "Average Cost",
    SKU.CREATED_BY                  AS "Created By",
    TO_CHAR(SKU.CREATION_DATE, 'dd/MM/yyyy hh24:mi:ss') AS "Creation Date",
    SKU.LAST_UPDATED_BY             AS "Last Updated By",
    TO_CHAR(SKU.LAST_UPDATE_DATE, 'dd/MM/yyyy hh24:mi:ss') AS "Last Update Date",
    SKU.EACH_QUANTITY               AS "Each Quantity",
    SKU.QC_STATUS                   AS "QC Status",
    SKU.SHELF_LIFE                  AS "Shelf Life",
    SKU.QC_FREQUENCY                AS "QC Frequency",
    SKU.QC_REC_COUNT                AS "QC Rec Count",
    SKU.SPLIT_LOWEST                AS "Split Lowest",
    SKU.CONDITION_REQD              AS "Condition Req'd",
    SKU.EXPIRY_REQD                 AS "Expiry Req'd",
    SKU.ORIGIN_REQD                 AS "Origin Req'd",
    SKU.SERIAL_AT_PACK              AS "Serial at Pack",
    SKU.SERIAL_AT_PICK              AS "Serial at Pick",
    SKU.SERIAL_AT_RECEIPT           AS "Serial at Receipt",
    SKU.SERIAL_RANGE                AS "Serial Range",
    SKU.SERIAL_FORMAT               AS "Serial Format",
    SKU.SERIAL_VALID_MERGE          AS "Serial Valid Merge",
    SKU.SERIAL_NO_REUSE             AS "Serial No Reuse",
    SKU.PICK_SEQUENCE               AS "Pick Sequence",
    SKU.PICK_COUNT_QTY              AS "Pick Count Qty",
    SKU.COUNT_FREQUENCY             AS "Count Frequency",
    TO_CHAR(SKU.COUNT_DSTAMP, 'dd/MM/yyyy hh24:mi:ss') AS "Count Dstamp",
    SKU.COUNT_LIST_ID               AS "Count List ID",
    SKU.OAP_WIP_ENABLED             AS "OAP WIP Enabled",
    SKU.KIT_SKU                     AS "Kit SKU",
    SKU.KIT_SPLIT                   AS "Kit Split",
    SKU.KIT_TRIGGER_QTY             AS "Kit Trigger Qty",
    SKU.KIT_QTY_DUE                 AS "Kit Qty Due",
    SKU.KITTING_LOC_ID              AS "Kitting Loc ID",
    SKU.ABC_DISABLE                 AS "ABC Disable",
    SKU.HANDLING_CLASS              AS "Handling Class",
    SKU.OBSOLETE_PRODUCT            AS "Obsolete Product",
    SKU.NEW_PRODUCT                 AS "New Product",
    SKU.DISALLOW_UPLOAD             AS "Disallow Upload",
    SKU.DISALLOW_CROSS_DOCK         AS "Disallow Cross Dock",
    SKU.MANUF_DSTAMP_REQD           AS "Manuf Dstamp Req'd",
    SKU.MANUF_DSTAMP_DFLT           AS "Manuf Dstamp Dflt",
    SKU.MIN_SHELF_LIFE              AS "Min Shelf Life",
    SKU.COLOUR                      AS "Colour",
    SKU.SKU_SIZE                    AS "SKU Size",
    SKU.SHIP_SHELF_LIFE             AS "Ship Shelf Life",
    SKU.NMFC_NUMBER                 AS "NMFC Number",
    SKU.INCUB_RULE                  AS "Incub Rule",
    SKU.INCUB_HOURS                 AS "Incub Hours",
    SKU.REORDER_TRIGGER_QTY         AS "Reorder Trigger Qty",
    SKU.LOW_TRIGGER_QTY             AS "Low Trigger Qty",
    SKU.DISALLOW_MERGE_RULES        AS "Disallow Merge Rules",
    SKU.PACK_DESPATCH_REPACK        AS "Pack Despatch Repack",
    SKU.SPEC_ID                     AS "Spec ID",
    SKU.USER_DEF_CHK_1              AS "Secure Item",
    SKU.USER_DEF_CHK_2              AS "Task Per Each",
    SKU.USER_DEF_CHK_3              AS "Reserved Stock Flag",
    SKU.USER_DEF_CHK_4              AS "Rework Required",
    TO_CHAR(SKU.USER_DEF_DATE_1, 'dd/MM/yyyy hh24:mi:ss') AS "User Def Date 1",
    TO_CHAR(SKU.USER_DEF_DATE_2, 'dd/MM/yyyy hh24:mi:ss') AS "User Def Date 2",
    TO_CHAR(SKU.USER_DEF_DATE_3, 'dd/MM/yyyy hh24:mi:ss') AS "User Def Date 3",
    TO_CHAR(SKU.USER_DEF_DATE_4, 'dd/MM/yyyy hh24:mi:ss') AS "User Def Date 4",
    SKU.USER_DEF_NOTE_1             AS "User Def Note 1",
    SKU.USER_DEF_NOTE_2             AS "User Def Note 2",
    SKU.CE_WAREHOUSE_TYPE           AS "CE Warehouse Type",
    SKU.CE_CUSTOMS_EXCISE           AS "CE Customs Excise",
    SKU.CE_STANDARD_COST            AS "CE Standard Cost",
    SKU.CE_STANDARD_CURRENCY        AS "CE Standard Currency",
    SKU.COUNT_LIST_ID_1             AS "Count List ID 1",
    SKU.DISALLOW_CLUSTERING         AS "Disallow Clustering",
    SKU.MAX_STACK                   AS "Max Stack",
    SKU.STACK_DESCRIPTION           AS "Stack Description",
    SKU.STACK_LIMITATION            AS "Stack Limitation",
    SKU.CE_DUTY_STAMP               AS "CE Duty Stamp",
    SKU.CAPTURE_WEIGHT              AS "Capture Weight",
    SKU.WEIGH_AT_RECEIPT            AS "Weigh at Receipt",
    SKU.UPPER_WEIGHT_TOLERANCE      AS "Upper Weight Tolerance",
    SKU.LOWER_WEIGHT_TOLERANCE      AS "Lower Weight Tolerance",
    SKU.SERIAL_AT_LOADING           AS "Serial at Loading",
    SKU.SERIAL_AT_KITTING           AS "Serial at Kitting",
    SKU.SERIAL_AT_UNKITTING         AS "Serial at Unkitting",
    SKU.ALLOCALG_LOCKING_STN        AS "Allocalg Locking Stn",
    SKU.PUTALG_LOCKING_STN          AS "Putalg Locking Stn",
    SKU.CE_COMMODITY_CODE           AS "CE Commodity Code",
    SKU.CE_COO                      AS "CE COO",
    SKU.CE_CWC                      AS "CE CWC",
    SKU.CE_VAT_CODE                 AS "CE VAT Code",
    SKU.CE_PRODUCT_TYPE             AS "CE Product Type",
    SKU.COMMODITY_CODE              AS "Commodity Code",
    SKU.COMMODITY_DESC              AS "Commodity Desc",
    SKU.FAMILY_GROUP                AS "Family Group",
    SKU.BREAKPACK                   AS "Breakpack",
    SKU.CLEARABLE                   AS "Clearable",
    SKU.STAGE_ROUTE_ID              AS "Stage Route ID",
    SKU.SERIAL_DYNAMIC_RANGE        AS "Serial Dynamic Range",
    SKU.SERIAL_MAX_RANGE            AS "Serial Max Range",
    SKU.MANUFACTURE_AT_REPACK       AS "Manufacture At Repack",
    SKU.EXPIRY_AT_REPACK            AS "Expiry At Repack",
    SKU.UDF_AT_REPACK               AS "UDF At Repack",
    SKU.REPACK_BY_PIECE             AS "Repack By Piece",
    SKU.TWO_MAN_LIFT                AS "Two Man Lift",
    SKU.AWKWARD                     AS "Awkward",
    SKU.DECATALOGUED                AS "Decatalogued",
    SKU.STOCK_CHECK_RULE_ID         AS "Stock Check Rule ID",
    SKU.UNKITTING_INHERIT           AS "Unkitting Inherit",
    SKU.SERIAL_AT_STOCK_CHECK       AS "Serial At Stock Check",
    SKU.SERIAL_AT_STOCK_ADJUST      AS "Serial At Stock Adjust",
    SKU.KIT_SHIP_COMPONENTS         AS "Kit Ship Components",
    SKU.UNALLOCATABLE               AS "Unallocatable",
    SKU.BATCH_AT_KITTING            AS "Batch At Kitting",
    SKU.SERIAL_PER_EACH             AS "Serial Per Each",
    SKU.BATCH_ID_GENERATION_ALG     AS "Batch ID Generation Alg",
    SKU.VMI_ALLOW_ALLOCATION        AS "VMI Allow Allocation",
    SKU.VMI_ALLOW_REPLENISH         AS "VMI Allow Replenish",
    SKU.VMI_ALLOW_MANUAL            AS "VMI Allow Manual",
    SKU.VMI_ALLOW_INTERFACED        AS "VMI Allow Interfaced",
    SKU.VMI_OVERSTOCK_QTY           AS "VMI Overstock Qty",
    SKU.VMI_AGING_DAYS              AS "VMI Aging Days",
    SKU.SCRAP_ON_RETURN             AS "Scrap On Return",
    SKU.ALWAYS_FULL_PALLET          AS "Always Full Pallet",
    SKU.BUSINESS_UNIT_CODE          AS "Business Unit Code",
    SKU.CARRIER_PALLET_MIXING       AS "Carrier Pallet Mixing",
    SKU.CARRIER_PRODUCT_TYPE        AS "Carrier Product Type",
    SKU.CE_ALCOHOLIC_STRENGTH       AS "CE Alcoholic Strength",
    SKU.CE_BRAND_NAME               AS "CE Brand Name",
    SKU.CE_COMMERCIAL_DESC          AS "CE Commercial Desc",
    SKU.CE_DEGREE_PLATO             AS "CE Degree Plato",
    SKU.CE_DENSITY                  AS "CE Density",
    SKU.CE_DESIGNATION_ORIGIN       AS "CE Designation Origin",
    SKU.CE_EXCISE_PRODUCT_CODE      AS "CE Excise Product Code",
    SKU.CE_FISCAL_MARK              AS "CE Fiscal Mark",
    SKU.CE_SIZE_OF_PRODUCER         AS "CE Size Of Producer",
    SKU.COLLATABLE                  AS "Collatable",
    SKU.CONVEYABLE                  AS "Conveyable",
    SKU.DISALLOW_RDT_OVER_PICKING   AS "Disallow RDT Over Picking",
    SKU.ECOMMERCE                   AS "Ecommerce",
    SKU.FOLDABLE                    AS "Foldable",
    SKU.FRAGILE                     AS "Fragile",
    SKU.FULL_PALLET_AT_RECEIPT      AS "Full Pallet At Receipt",
    SKU.GENDER                      AS "Gender",
    SKU.HANGING_GARMENT             AS "Hanging Garment",
    SKU.HARMONISED_PRODUCT_CODE     AS "Harmonised Product Code",
    SKU.HIGH_SECURITY               AS "High Security",
    SKU.NO_ALLOC_BACK_ORDER         AS "No Alloc Back Order",
    SKU.PROMOTION                   AS "Promotion",
    SKU.RETURN_MIN_SHELF_LIFE       AS "Return Min Shelf Life",
    SKU.SERIAL_CHECK_STRING         AS "Serial Check String",
    SKU.SERIAL_NO_OUTBOUND          AS "Serial No Outbound",
    SKU.SPECIAL_CONTAINER_TYPE      AS "Special Container Type",
    SKU.STYLE                       AS "Style",
    SKU.SUB_WITHIN_PRODUCT_GRP      AS "Sub Within Product Grp",
    SKU.TAG_MERGE                   AS "Tag Merge",
    SKU.UGLY                        AS "Ugly",
    SKU.UPLOADED                    AS "Uploaded",
    TO_CHAR(SKU.UPLOADED_DSTAMP, 'dd/MM/yyyy hh24:mi:ss') AS "Uploaded DStamp",
    SKU.UPLOADED_FILENAME           AS "Uploaded Filename",
    SKU.UPLOADED_WS2PC_ID           AS "Uploaded WS2PC ID",
    SKU.WEIGH_AT_GRID_PICK          AS "Weigh At Grid Pick"
FROM
    SKU
WHERE
    -- SKU.SKU_ID LIKE 'GN21%'  AND 
   ROWNUM < 50
